# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 986d352f2677879b48564fae2f7e65485d7120a97a6974e298614ebc0bfc1e4822c58c8142a0fd4181440060070f67c5b5fff48093f7cbc2cbf2eb6c9322b9f7

test:
  secret_key_base: 93b9cb548fecba3190e0f6649dec52b2e0051f38db11272ff23db273a4918a7f96adb85b8213ff3c261202fe4f792e3de3998b447e9c9284f0119a272209456e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
